-- OmegaSpell - cache genere depuis WTF.
-- Genere le 2026-05-02 16:39:55.

OmegaSpellWTFMacroCache = {
    generatedAt = "2026-05-02 16:39:55",
    profiles = {
        {
            key = "WTF:GLOBAL",
            label = "Global",
            account = "",
            realm = "",
            character = "",
            type = "global",
            macros = {
                {
                    id = "000000000000002C",
                    name = "/os",
                    displayName = "/os",
                    icon = "Interface/Icons/eps_bg3_bhaal2",
                    body = "/omsp s rituel",
                },
                {
                    id = "000000000000002A",
                    name = "/reload",
                    displayName = "/reload",
                    icon = "1373910",
                    body = "/reload",
                },
                {
                    id = "0000000000000001",
                    name = "A'Hell'Razkah",
                    displayName = "A'Hell'Razkah",
                    icon = "135754",
                    body = ".phase enter 158070 here",
                },
                {
                    id = "0000000000000017",
                    name = "Arme Dégainer",
                    displayName = "Arme Dégainer",
                    icon = "135129",
                    body = "/run SendChatMessage(IsAltKeyDown()and\".unaura 199832\"or\".aura 199832\",\"YELL\")",
                },
                {
                    id = "0000000000000007",
                    name = "Assis - H",
                    displayName = "Assis - H",
                    icon = "INV_MISC_QUESTIONMARK",
                    body = ".mod sit",
                },
                {
                    id = "0000000000000010",
                    name = "Assis - H - Pira",
                    displayName = "Assis - H - Pira",
                    icon = "INV_MISC_QUESTIONMARK",
                    body = "/run SendChatMessage(IsAltKeyDown()and\".unaura 278498\"or\".aura 278498\",\"YELL\")",
                },
                {
                    id = "000000000000002D",
                    name = "Aura de connard",
                    displayName = "Aura de connard",
                    icon = "136012",
                    body = "/run SendChatMessage(IsAltKeyDown()and\".unaura 39092\"or\".aura 39092\",\"YELL\")",
                },
                {
                    id = "0000000000000005",
                    name = "Aura Zone",
                    displayName = "Aura Zone",
                    icon = "INV_MISC_QUESTIONMARK",
                    body = ".phase enter 16000",
                },
                {
                    id = "0000000000000014",
                    name = "Bank",
                    displayName = "Bank",
                    icon = "132761",
                    body = ".cheat bank",
                },
                {
                    id = "000000000000000D",
                    name = "Contre mur",
                    displayName = "Contre mur",
                    icon = "INV_MISC_QUESTIONMARK",
                    body = ".mod stand 720",
                },
                {
                    id = "000000000000001A",
                    name = "Coup G>D Epée",
                    displayName = "Coup G>D Epée",
                    icon = "135291",
                    body = ".cast 6572",
                },
                {
                    id = "000000000000001B",
                    name = "Coup Rota Epée",
                    displayName = "Coup Rota Epée",
                    icon = "132119",
                    body = ".cast 1680",
                },
                {
                    id = "000000000000000A",
                    name = "Death Aura",
                    displayName = "Death Aura",
                    icon = "132090",
                    body = "/run SendChatMessage(IsAltKeyDown()and\".unaura 85267\"or\".aura 85267\",\"YELL\")",
                },
                {
                    id = "0000000000000024",
                    name = "Death PNJ",
                    displayName = "Death PNJ",
                    icon = "132094",
                    body = "/run SendChatMessage(IsAltKeyDown()and\".npc set unaura 85267\"or\".npc set aura 85267\",\"YELL\")",
                },
                {
                    id = "000000000000001C",
                    name = "Degainage temps",
                    displayName = "Degainage temps",
                    icon = "2065616",
                    body = "/run SendChatMessage(IsAltKeyDown()and\".unaura 199832\"or\".aura 199832\",\"YELL\")\n/run SendChatMessage(IsAltKeyDown()and\".cast 328620\"or\".cast 328282\",\"YELL\")",
                },
                {
                    id = "000000000000000F",
                    name = "Frotter sol",
                    displayName = "Frotter sol",
                    icon = "INV_MISC_QUESTIONMARK",
                    body = ".mod stand 720",
                },
                {
                    id = "000000000000000B",
                    name = "GM ON",
                    displayName = "GM ON",
                    icon = "136012",
                    body = ".mod sc 1.075\n.mod sp 1\n.mod hp 14\n.cheat god off\n.cheat cooldown on\n.cheat fly off\n.ph dm off",
                },
                {
                    id = "0000000000000013",
                    name = "Invisi PNJ",
                    displayName = "Invisi PNJ",
                    icon = "136103",
                    body = "/run SendChatMessage(IsAltKeyDown()and\".npc set unaura 37803\"or\".npc set aura 37803\",\"YELL\")",
                },
                {
                    id = "0000000000000012",
                    name = "Invisible",
                    displayName = "Invisible",
                    icon = "136103",
                    body = "/run SendChatMessage(IsAltKeyDown()and\".unaura 37803\"or\".aura 37803\",\"YELL\")",
                },
                {
                    id = "000000000000002B",
                    name = "lmining",
                    displayName = "lmining",
                    icon = "642417",
                    body = "/rnd +11 Adresse\n/rnd +11 Adresse\n/rnd +11 Adresse\n============\n/rnd +11 Adresse\n/rnd +11 Adresse\n/rnd +11 Adresse\n=============\n/rnd +11 Adresse\n/rnd +11 Adresse\n/rnd +11 Adresse\n=============\n/rnd +11 Adresse\n/rnd +11 Adresse\n/rnd +11 Adresse\n==========",
                },
                {
                    id = "0000000000000003",
                    name = "Macro spell Back",
                    displayName = "Macro spell Back",
                    icon = "INV_MISC_QUESTIONMARK",
                    body = "/run SendChatMessage(\"Id : \"..da)print(da)\n/run if da==null then da=561469 end\n/run SendChatMessage(\".cast \"..da)print(da)da=da-1",
                },
                {
                    id = "0000000000000002",
                    name = "Macro Spell Test",
                    displayName = "Macro Spell Test",
                    icon = "INV_MISC_QUESTIONMARK",
                    body = "/run SendChatMessage(\"Id : \"..da)print(da)\n/run if da==null then da=136 end\n/run SendChatMessage(\".cast \"..da)print(da)da=da+1",
                },
                {
                    id = "0000000000000009",
                    name = "Menotter",
                    displayName = "Menotter",
                    icon = "136102",
                    body = "/run SendChatMessage(IsAltKeyDown()and\".unaura 99365\"or\".aura 99365\",\"YELL\")",
                },
                {
                    id = "000000000000001E",
                    name = "NPC Del",
                    displayName = "NPC Del",
                    icon = "136175",
                    body = ".n d",
                },
                {
                    id = "0000000000000006",
                    name = "Phase Eindhill",
                    displayName = "Phase Eindhill",
                    icon = "236351",
                    body = ".ph en 178406",
                },
                {
                    id = "0000000000000015",
                    name = "Phase Val'Razkah",
                    displayName = "Phase Val'Razkah",
                    icon = "136103",
                    body = ".phase enter 195031",
                },
                {
                    id = "0000000000000018",
                    name = "PNJ Dégainer",
                    displayName = "PNJ Dégainer",
                    icon = "132395",
                    body = "/run SendChatMessage(IsAltKeyDown()and\".n set unaura 199832\"or\".n set aura 199832\",\"YELL\")",
                },
                {
                    id = "0000000000000011",
                    name = "Porter une caiss",
                    displayName = "Porter une caiss",
                    icon = "413587",
                    body = "/run SendChatMessage(IsAltKeyDown()and\".unaura 255013\"or\".aura 255013\",\"YELL\")",
                },
                {
                    id = "000000000000000E",
                    name = "Posture droite",
                    displayName = "Posture droite",
                    icon = "INV_MISC_QUESTIONMARK",
                    body = ".mod stand 714",
                },
                {
                    id = "0000000000000019",
                    name = "Rage de Mama",
                    displayName = "Rage de Mama",
                    icon = "236299",
                    body = ".n cast 353706",
                },
                {
                    id = "000000000000000C",
                    name = "Se lever",
                    displayName = "Se lever",
                    icon = "135871",
                    body = ".unaura 176572\n.gps up 1\n.cheat fly off",
                },
                {
                    id = "000000000000001D",
                    name = "Sneaky",
                    displayName = "Sneaky",
                    icon = "775461",
                    body = "/run SendChatMessage(IsAltKeyDown()and\".unaura 93046\"or\".aura 93046\",\"YELL\")",
                },
                {
                    id = "0000000000000025",
                    name = "Sonné",
                    displayName = "Sonné",
                    icon = "136175",
                    body = "/run SendChatMessage(IsAltKeyDown()and\".unaura 244807\"or\".aura 244807\",\"YELL\")",
                },
                {
                    id = "0000000000000027",
                    name = "Teleport NewScar",
                    displayName = "Teleport NewScar",
                    icon = "136103",
                    body = ".ph tel New",
                },
                {
                    id = "0000000000000026",
                    name = "Teleport PNJ",
                    displayName = "Teleport PNJ",
                    icon = "136103",
                    body = ".ph tel PNJ - Val",
                },
                {
                    id = "000000000000001F",
                    name = "Tenir fusil",
                    displayName = "Tenir fusil",
                    icon = "132217",
                    body = "/run SendChatMessage(IsAltKeyDown()and\".unaura 16723\"or\".aura 16723\",\"YELL\")",
                },
                {
                    id = "0000000000000008",
                    name = "Tenir livre - MG",
                    displayName = "Tenir livre - MG",
                    icon = "442732",
                    body = "/run SendChatMessage(IsAltKeyDown()and\".unaura 274046\"or\".aura 274046\",\"YELL\")",
                },
                {
                    id = "0000000000000020",
                    name = "Tir de fusil",
                    displayName = "Tir de fusil",
                    icon = "135610",
                    body = ".cast 1516",
                },
                {
                    id = "0000000000000004",
                    name = "Unaura All",
                    displayName = "Unaura All",
                    icon = "135871",
                    body = ".unaura all",
                },
                {
                    id = "0000000000000016",
                    name = "Val'Rakzah",
                    displayName = "Val'Rakzah",
                    icon = "136050",
                    body = ".phase enter 195031",
                },
                {
                    id = "0000000000000029",
                    name = "Vault Close",
                    displayName = "Vault Close",
                    icon = "611417",
                    body = "/sf 0045241002",
                },
                {
                    id = "0000000000000028",
                    name = "Vault Open",
                    displayName = "Vault Open",
                    icon = "611417",
                    body = "/sf 0045241001",
                },
                {
                    id = "0000000000000021",
                    name = "Visée debout",
                    displayName = "Visée debout",
                    icon = "135610",
                    body = "/run SendChatMessage(IsAltKeyDown()and\".unaura 79841\"or\".aura 79841\",\"YELL\")",
                },
                {
                    id = "0000000000000022",
                    name = "Visée à genou",
                    displayName = "Visée à genou",
                    icon = "135610",
                    body = "/run SendChatMessage(IsAltKeyDown()and\".unaura 145028\"or\".aura 145028\",\"YELL\")",
                },
                {
                    id = "0000000000000023",
                    name = "Waypoint Add",
                    displayName = "Waypoint Add",
                    icon = "1056569",
                    body = ".waypoint add",
                },
                {
                    id = "0000000000000007",
                    name = "/Reload",
                    displayName = "/Reload",
                    icon = "252182",
                    body = "/reload",
                },
                {
                    id = "0000000000000005",
                    name = "1D20",
                    displayName = "1D20",
                    icon = "237285",
                    body = "/rd 1d20 +5 Jet de test",
                },
                {
                    id = "0000000000000009",
                    name = "1d6",
                    displayName = "1d6",
                    icon = "237285",
                    body = "/rd 1d6",
                },
                {
                    id = "0000000000000006",
                    name = "2D20",
                    displayName = "2D20",
                    icon = "237285",
                    body = "/rd 2d20 +5 Dés de test",
                },
                {
                    id = "0000000000000008",
                    name = "6D20",
                    displayName = "6D20",
                    icon = "237285",
                    body = "/rd 6d20 +7 Dés de test",
                },
                {
                    id = "0000000000000003",
                    name = "Invisible",
                    displayName = "Invisible",
                    icon = "132130",
                    body = "/run SendChatMessage(IsAltKeyDown()and\".unaura 37803\"or\".aura 37803\",\"YELL\")",
                },
                {
                    id = "0000000000000001",
                    name = "Ph Eindhill",
                    displayName = "Ph Eindhill",
                    icon = "236206",
                    body = ".ph en 178406",
                },
                {
                    id = "0000000000000004",
                    name = "Reset Aura",
                    displayName = "Reset Aura",
                    icon = "878234",
                    body = ".unaura all",
                },
                {
                    id = "0000000000000002",
                    name = "Sneak",
                    displayName = "Sneak",
                    icon = "132938",
                    body = "/run SendChatMessage(IsAltKeyDown()and\".unaura 93046\"or\".aura 93046\",\"YELL\")",
                },
            },
        },
        {
            key = "WTF:Apertus:Khij'azi",
            label = "Khij'azi - Apertus",
            account = "AKRIAX",
            realm = "Apertus",
            character = "Khij'azi",
            type = "character",
            macros = {
                {
                    id = "0100000000000001",
                    name = "Cast PNJ Sang",
                    displayName = "Cast PNJ Sang",
                    icon = "538040",
                    body = "/run SendChatMessage(IsAltKeyDown()and\".n se unaura 277983\"or\".n set aura 277983\",\"YELL\")",
                },
                {
                    id = "0100000000000003",
                    name = "NPC Create",
                    displayName = "NPC Create",
                    icon = "136037",
                    body = "",
                },
                {
                    id = "0100000000000002",
                    name = "Way Add",
                    displayName = "Way Add",
                    icon = "236299",
                    body = ".waypoint add",
                },
            },
        },
        {
            key = "WTF:Apertus:Talyah",
            label = "Talyah - Apertus",
            account = "AKRIAX",
            realm = "Apertus",
            character = "Talyah",
            type = "character",
            macros = {
                {
                    id = "0100000000000002",
                    name = ".n info",
                    displayName = ".n info",
                    icon = "INV_MISC_QUESTIONMARK",
                    body = ".n info",
                },
                {
                    id = "0100000000000001",
                    name = ".ph f n create",
                    displayName = ".ph f n create",
                    icon = "132627",
                    body = ".ph f np create 83918\n.ph f np create 68730\n.ph f np create 65636\n.ph f np create 83649\n.ph f np create 55415\n.ph f np create 55416\n.ph f np create 55520\n.ph f np create 55414\n.ph f np create 57545\n.ph f np create 57231\n.ph f np create 57899",
                },
                {
                    id = "0100000000000003",
                    name = "/os",
                    displayName = "/os",
                    icon = "136103",
                    body = "/os",
                },
            },
        },
        {
            key = "WTF:Apertus:Svalgard",
            label = "Svalgard - Apertus",
            account = "AKRIAX, AKRX",
            realm = "Apertus",
            character = "Svalgard",
            type = "character",
            macros = {
                {
                    id = "0100000000000001",
                    name = "Can Ombre T5",
                    displayName = "Can Ombre T5",
                    icon = "136096",
                    body = ".cast 225305",
                },
                {
                    id = "0100000000000004",
                    name = "1 - GM On",
                    displayName = "1 - GM On",
                    icon = "133564",
                    body = ".gm on\n.mod sp 1\n.mod sc 1\n.ph dm off\n.demorph\n.cheat fly off\n.cheat god off\n.mod hp 40\n.refresh",
                },
                {
                    id = "0100000000000001",
                    name = "Cast 1 - Nécro",
                    displayName = "Cast 1 - Nécro",
                    icon = "132107",
                    body = ".cast 343505",
                },
                {
                    id = "0100000000000002",
                    name = "Cast 2 - AOE",
                    displayName = "Cast 2 - AOE",
                    icon = "132101",
                    body = ".cast 333138",
                },
                {
                    id = "0100000000000003",
                    name = "Sphère nécro",
                    displayName = "Sphère nécro",
                    icon = "135799",
                    body = "/run SendChatMessage(IsAltKeyDown()and\".unaura 343798\"or\".aura 343798\",\"YELL\")",
                },
            },
        },
        {
            key = "WTF:Apertus:Moohn",
            label = "Moohn - Apertus",
            account = "AKRIAX",
            realm = "Apertus",
            character = "Moohn",
            type = "character",
            macros = {
                {
                    id = "0100000000000002",
                    name = "GM On",
                    displayName = "GM On",
                    icon = "134153",
                    body = ".gm on\n.cheat fly off\n.demorph\n.mod sc 1.07\n.mod sp .8\n.ph dm off",
                },
                {
                    id = "0100000000000004",
                    name = "OS0001",
                    displayName = "OS0001",
                    icon = "134442",
                    body = "/omsp id OS0001",
                },
                {
                    id = "0100000000000003",
                    name = "OS: Arms behind ",
                    displayName = "OS: Arms behind ",
                    icon = "236314",
                    body = "/omsp cast Arms behind Back",
                },
                {
                    id = "0100000000000001",
                    name = "Unlickable",
                    displayName = "Unlickable",
                    icon = "132089",
                    body = ".ph f n click",
                },
            },
        },
        {
            key = "WTF:Apertus:Ashaltaar",
            label = "Ashaltaar - Apertus",
            account = "AKRIAX",
            realm = "Apertus",
            character = "Ashaltaar",
            type = "character",
            macros = {
                {
                    id = "010000000000000A",
                    name = "Attaque",
                    displayName = "Attaque",
                    icon = "133479",
                    body = ".n cast creatu 283424 16206583",
                },
                {
                    id = "0100000000000009",
                    name = "Attaque rotation",
                    displayName = "Attaque rotation",
                    icon = "132147",
                    body = ".n cast creatu 1680 16206583",
                },
                {
                    id = "0100000000000007",
                    name = "Casque Nefheld",
                    displayName = "Casque Nefheld",
                    icon = "132212",
                    body = ".aura 45725",
                },
                {
                    id = "0100000000000001",
                    name = "Cocon de Vie",
                    displayName = "Cocon de Vie",
                    icon = "132840",
                    body = "/run SendChatMessage(IsAltKeyDown()and\".unaura 165128\"or\".aura 165128\",\"YELL\")",
                },
                {
                    id = "0100000000000008",
                    name = "Empallement",
                    displayName = "Empallement",
                    icon = "132317",
                    body = ".n cast creatu 207735 16206583",
                },
                {
                    id = "0100000000000004",
                    name = "Frappe de Chi",
                    displayName = "Frappe de Chi",
                    icon = "132318",
                    body = ".cast 100780",
                },
                {
                    id = "0100000000000005",
                    name = "GM On",
                    displayName = "GM On",
                    icon = "606552",
                    body = ".mod hp 150\n.mod sc 1.04\n.mod sp .85\n.cheat god off",
                },
                {
                    id = "010000000000000B",
                    name = "Gnom Fruit",
                    displayName = "Gnom Fruit",
                    icon = "642415",
                    body = "/run SendChatMessage(IsAltKeyDown()and\".n set unaura 301968\"or\".n set aura 301968\",\"YELL\")",
                },
                {
                    id = "0100000000000003",
                    name = "King of fury",
                    displayName = "King of fury",
                    icon = "2576095",
                    body = ".cast 119014",
                },
                {
                    id = "010000000000000C",
                    name = "NPC Create",
                    displayName = "NPC Create",
                    icon = "611417",
                    body = ".ph f n create\n.ph f n create\n.ph f n create\n.ph f n create\n.ph f n create\n.ph f n create\n.ph f n create\n.ph f n create\n.ph f n create\n.ph f n create\n.ph f n create\n.ph f n create\n.ph f n create\n.ph f n create\n.ph f n create\n.ph f n create\n.ph f n create",
                },
                {
                    id = "0100000000000002",
                    name = "Rotating Kick",
                    displayName = "Rotating Kick",
                    icon = "574571",
                    body = ".cast 100784",
                },
                {
                    id = "0100000000000006",
                    name = "Sneaking",
                    displayName = "Sneaking",
                    icon = "132089",
                    body = "/run SendChatMessage(IsAltKeyDown()and\".unaura 93046\"or\".aura 93046\",\"YELL\")",
                },
            },
        },
        {
            key = "WTF:Apertus:Erzah",
            label = "Erzah - Apertus",
            account = "AKRIAX",
            realm = "Apertus",
            character = "Erzah",
            type = "character",
            macros = {
                {
                    id = "0100000000000005",
                    name = "Atk Dis",
                    displayName = "Atk Dis",
                    icon = "135493",
                    body = "/rd 1d20+3 Atk. Distance",
                },
                {
                    id = "0100000000000009",
                    name = "Atk Mag",
                    displayName = "Atk Mag",
                    icon = "132128",
                    body = "/rd 1d20+4 Atk. Magique",
                },
                {
                    id = "0100000000000006",
                    name = "Atk Phy",
                    displayName = "Atk Phy",
                    icon = "132392",
                    body = "/rd 1d20+3 Atk. Physique",
                },
                {
                    id = "010000000000000C",
                    name = "Bulle temporelle",
                    displayName = "Bulle temporelle",
                    icon = "236151",
                    body = "/run SendChatMessage(IsAltKeyDown()and\".unaura 301434\"or\".aura 301434\",\"YELL\")",
                },
                {
                    id = "0100000000000011",
                    name = "Clone Temporelle",
                    displayName = "Clone Temporelle",
                    icon = "135939",
                    body = ".n spawn 2260535\n.unau 252620\n.unau 293019\n.unau 305141\n.aura 37803",
                },
                {
                    id = "0100000000000007",
                    name = "Dmg Dist",
                    displayName = "Dmg Dist",
                    icon = "236216",
                    body = "/rd 2d10+2 Dégats Dist. [Crit = Paralysie ( 2 Tours ) }",
                },
                {
                    id = "010000000000000A",
                    name = "Dmg Mag",
                    displayName = "Dmg Mag",
                    icon = "132286",
                    body = "/rd 1d6",
                },
                {
                    id = "0100000000000008",
                    name = "Dmg Phys",
                    displayName = "Dmg Phys",
                    icon = "132090",
                    body = "/rd 1d20 Dégats CaC",
                },
                {
                    id = "0100000000000014",
                    name = "Détonnation temp",
                    displayName = "Détonnation temp",
                    icon = "132207",
                    body = ".cast 283362\n/in 0.6 /e .cast 251695",
                },
                {
                    id = "0100000000000010",
                    name = "Eveil activation",
                    displayName = "Eveil activation",
                    icon = "136017",
                    body = ".go spa 209249\n.go sc 0.09\n.go spe 237555\n.n spawn 2260384",
                },
                {
                    id = "010000000000000D",
                    name = "Gun Ready",
                    displayName = "Gun Ready",
                    icon = "135610",
                    body = "/run SendChatMessage(IsAltKeyDown()and\".unaura 275018\"or\".aura 275018\",\"YELL\")",
                },
                {
                    id = "010000000000000B",
                    name = "Impact Temp",
                    displayName = "Impact Temp",
                    icon = "413591",
                    body = ".cast 275806",
                },
                {
                    id = "0100000000000012",
                    name = "Lanceur spell",
                    displayName = "Lanceur spell",
                    icon = "236316",
                    body = "/run SendChatMessage(IsAltKeyDown()and\".unaura 136174\"or\".aura 136174\",\"YELL\")",
                },
                {
                    id = "0100000000000015",
                    name = "Lien temporelle",
                    displayName = "Lien temporelle",
                    icon = "132309",
                    body = "/run SendChatMessage(IsAltKeyDown() and \".unaura 268345\" or \".cast 268345\",\"YELL\")",
                },
                {
                    id = "010000000000000F",
                    name = "Lévitation",
                    displayName = "Lévitation",
                    icon = "132171",
                    body = "/run SendChatMessage(IsAltKeyDown()and\".unaura 252620\"or\".aura 252620\",\"YELL\")\n/run SendChatMessage(IsAltKeyDown()and\".unaura 293019\"or\".aura 293019\",\"YELL\")\n/run SendChatMessage(IsAltKeyDown()and\".unaura 305141\"or\".aura 305141\",\"YELL\")\n.unau 37803",
                },
                {
                    id = "0100000000000004",
                    name = "Tenir fusil",
                    displayName = "Tenir fusil",
                    icon = "132217",
                    body = "/run SendChatMessage(IsAltKeyDown()and\".unaura 16723\"or\".aura 16723\",\"YELL\")",
                },
                {
                    id = "0100000000000001",
                    name = "Tir de fusil",
                    displayName = "Tir de fusil",
                    icon = "135610",
                    body = ".cast 1516",
                },
                {
                    id = "010000000000000E",
                    name = "Tranche Temporel",
                    displayName = "Tranche Temporel",
                    icon = "135561",
                    body = ".cast 328305",
                },
            },
        },
        {
            key = "WTF:Apertus:Svenbaldr",
            label = "Svenbaldr - Apertus",
            account = "AKRX",
            realm = "Apertus",
            character = "Svenbaldr",
            type = "character",
            macros = {
                {
                    id = "0100000000000002",
                    name = "Atk",
                    displayName = "Atk",
                    icon = "132223",
                    body = "/rd 1d20+5 Atk Phy",
                },
                {
                    id = "0100000000000003",
                    name = "Dm P",
                    displayName = "Dm P",
                    icon = "135129",
                    body = "/rd 1d20+2 DM",
                },
                {
                    id = "0100000000000001",
                    name = "GM On",
                    displayName = "GM On",
                    icon = "132353",
                    body = ".gm on\n.cheat god off\n.phase dm off\n.mod hp 21\n.cheat fly off\n.cheat cooldown on\n.demorph\n.mod sc 1.05\n.mod sp 1",
                },
            },
        },
    },
}
