-- GrimoireCraft - Base officielle des objets
-- Database intégrée depuis « GrimoireCraft — Database Maître » (Google Drive).
-- Les doublons d’ID du tableur sont fusionnés en une seule entrée.

GrimoireCraftOfficialObjects = {
    [14072525] = { name="Minerais d'Acier", usage="Composant", notes="ID confirmé via scanner marchand" },
    [14072526] = { name="Minerais de Cuivre", usage="Composant", notes="ID confirmé via scanner marchand" },
    [14072527] = { name="Alun de Roche", usage="Composant", notes="ID confirmé via scanner marchand" },
    [14072528] = { name="Minerais de Fer Noir", usage="Composant", notes="ID confirmé via scanner marchand" },
    [14072529] = { name="Corolle de Dorevan", usage="Composant", notes="ID confirmé via scanner marchand" },
    [14072530] = { name="Minerais de Skodelite", usage="Composant", notes="ID confirmé via scanner marchand" },
    [14072531] = { name="Lys des Rosées", usage="Composant", notes="ID confirmé via scanner marchand" },
    [14072532] = { name="Primevère de Vitriol", usage="Composant", notes="ID confirmé via scanner marchand" },
    [14072533] = { name="Rose d'Antimoine", usage="Composant", notes="ID confirmé via scanner marchand" },
    [14072534] = { name="Chardon de Plaie-de-Nuit", usage="Composant", notes="ID confirmé via scanner marchand" },
    [14072535] = { name="Chèvrefeuille de l'Hermite", usage="Composant", notes="ID confirmé via scanner marchand" },
    [14072536] = { name="Ambre du Fjord", usage="Composant", notes="ID confirmé via scanner marchand" },
    [14072537] = { name="Mousse Chatoyante", usage="Composant", notes="ID confirmé via scanner marchand" },
    [14072538] = { name="Sauge de Bleuée", usage="Composant", notes="ID confirmé via scanner marchand" },
    [14072539] = { name="Sève de Vie", usage="Composant", notes="ID confirmé via scanner marchand" },
    [14072540] = { name="Lichen de Runavik", usage="Composant", notes="ID confirmé via scanner marchand" },
    [14072541] = { name="Lys de Glace d'Hudra", usage="Composant", notes="ID confirmé via scanner marchand" },
    [14072542] = { name="Poudre d'Aile de Givre Animée", usage="Composant", notes="ID confirmé via scanner marchand" },
    [14072543] = { name="Ombelle d'Argent", usage="Composant", notes="ID confirmé via scanner marchand" },
    [14072544] = { name="Écorce de Skard", usage="Composant", notes="ID confirmé via scanner marchand" },
    [14072545] = { name="Givre Condensé", usage="Composant", notes="ID confirmé via scanner marchand" },
    [14072546] = { name="Souffle Tellurique", usage="Composant", notes="ID confirmé via scanner marchand" },
    [14072547] = { name="Baies de Genièvre", usage="Composant", notes="ID confirmé via scanner marchand" },
    [14072548] = { name="Oignon Sauvage", usage="Composant", notes="ID confirmé via scanner marchand" },
    [14072549] = { name="Baies d'Argousier", usage="Composant", notes="ID confirmé via scanner marchand" },
    [14072550] = { name="Racine de Njordford", usage="Composant", notes="ID confirmé via scanner marchand" },
    [14072551] = { name="Peau de Gibier", usage="Composant", notes="ID confirmé via scanner marchand" },
    [14072552] = { name="Peau de Gibier Skolagien", usage="Composant", notes="ID confirmé via scanner marchand" },
    [14072553] = { name="Viande de Gibier", usage="Composant", notes="ID confirmé via scanner marchand" },
    [14072554] = { name="Viande de Gibier Skolagien", usage="Composant", notes="ID confirmé via scanner marchand" },
    [14072555] = { name="Miel des Forêts", usage="Composant", notes="ID confirmé via scanner marchand" },
    [14072556] = { name="Cire d'Abeille Brute", usage="Composant", notes="ID confirmé via scanner marchand" },
    [14072557] = { name="Cire Hivernale", usage="Composant", notes="ID confirmé via scanner marchand" },
    [14072652] = { name="Pavois Solide", category="Armement / Bouclier", usage="Nouvel objet scanner", notes="ID confirmé via scanner marchand" },
    [14072709] = { name="Flèche Glacée", category="Projectiles", usage="Nouvel objet scanner", notes="ID confirmé via scanner marchand" },
    [14072723] = { name="Cape du Loup Décorée de Runes", category="Secondaire / Equipement", usage="Nouvel objet scanner", notes="ID confirmé via scanner marchand" },
    [14072728] = { name="Pièce d'Or", category="Monnaie", usage="Monnaie" },
    [14072774] = { name="Objet Commun", category="Trésor", usage="Nouvel objet scanner", notes="ID confirmé via scanner marchand" },
    [14072775] = { name="Objet Rare", category="Trésor", usage="Nouvel objet scanner", notes="ID confirmé via scanner marchand" },
    [14072776] = { name="Objet Epique", category="Trésor", usage="Nouvel objet scanner", notes="ID confirmé via scanner marchand" },
    [14072777] = { name="Objet Légendaire", category="Trésor", usage="Nouvel objet scanner", notes="ID confirmé via scanner marchand" },
    [14072807] = { name="Outils de Crochetage", category="Objet / Consommable", usage="Objet / Consommable" },
    [14072810] = { name="Carnet de Survie", category="Outil", usage="Outil" },
    [14072827] = { name="Charbon", usage="Composant", notes="ID confirmé via scanner marchand" },
    [14072829] = { name="Libram du Dévot", category="Maîtrise / Outils", usage="Nouvel objet scanner", notes="ID confirmé via scanner marchand" },
    [14072836] = { name="Sel de Roche", usage="Composant", notes="ID confirmé via scanner marchand" },
    [14072839] = { name="Dé à Coudre", category="Outil", usage="Outil" },
    [14072840] = { name="Aiguille", category="Outil", usage="Outil" },
    [14072841] = { name="Mallette d’Ingénieur", category="Outil", usage="Outil" },
    [14072842] = { name="Vis en Cuivre", usage="Objet fabriqué + Composant", notes="ID confirmé via scanner marchand" },
    [14072843] = { name="Fiole", usage="Objet fabriqué + Composant", notes="ID confirmé via scanner marchand" },
    [14072844] = { name="Mortier et Pilon", category="Outil", usage="Outil" },
    [14072846] = { name="Marteau de Forge", category="Outil", usage="Outil" },
    [14072863] = { name="Elixir de Maîtrise II", category="Elixir / Consommable", usage="Nouvel objet scanner", notes="ID confirmé via scanner marchand" },
    [14072869] = { name="Bandage Simple", usage="Objet fabriqué", notes="ID confirmé via scanner marchand" },
    [14072870] = { name="Bandage Lourd", usage="Objet fabriqué", notes="ID confirmé via scanner marchand" },
    [14072874] = { name="Parchemin de Respiration Aquatique", category="Parchemin / Consommable", usage="Nouvel objet scanner", notes="ID confirmé via scanner marchand" },
    [14072876] = { name="Parchemin de Maîtrise Enchanté", category="Parchemin / Consommable", usage="Nouvel objet scanner", notes="ID confirmé via scanner marchand" },
    [14072901] = { name="Glyphe de Feu", category="Objet / Consommable", usage="Nouvel objet scanner", notes="ID confirmé via scanner marchand" },
    [14072902] = { name="Glyphe d’Eau", category="Objet / Consommable", usage="Nouvel objet scanner", notes="ID confirmé via scanner marchand" },
    [14072903] = { name="Glyphe de Terre", category="Objet / Consommable", usage="Nouvel objet scanner", notes="ID confirmé via scanner marchand" },
    [14072904] = { name="Glyphe d’Air", category="Objet / Consommable", usage="Nouvel objet scanner", notes="ID confirmé via scanner marchand" },
    [14072905] = { name="Glyphe de Chaos", category="Objet / Consommable", usage="Nouvel objet scanner", notes="ID confirmé via scanner marchand" },
    [14072906] = { name="Glyphe d’Ombre", category="Objet / Consommable", usage="Nouvel objet scanner", notes="ID confirmé via scanner marchand" },
    [14072907] = { name="Glyphe de Maîtrise", category="Objet / Consommable", usage="Nouvel objet scanner", notes="ID confirmé via scanner marchand" },
    [14072908] = { name="Glyphe de Lumière", category="Objet / Consommable", usage="Nouvel objet scanner", notes="ID confirmé via scanner marchand" },
    [14072910] = { name="Minerais Stellaires", usage="Composant", notes="ID confirmé via scanner marchand" },
    [14072911] = { name="Lingot Astral", usage="Objet fabriqué + Composant", notes="ID confirmé via scanner marchand" },
    [14072913] = { name="Lingot Runique", usage="Objet fabriqué + Composant", notes="ID confirmé via scanner marchand" },
    [14072914] = { name="Minerais Runifiés", usage="Composant", notes="ID confirmé via scanner marchand" },
    [14072919] = { name="Fiole Enchantée", category="Alchimie / Maîtrise / Outils", usage="Nouvel objet scanner", notes="ID confirmé via scanner marchand" },
    [14072920] = { name="Fiole Gravée", category="Composant", usage="Composant" },
    [14072939] = { name="Hydromel des Dieux", category="Boisson / Consommable", usage="Nouvel objet scanner", notes="ID confirmé via scanner marchand" },
    [14072947] = { name="Livre de Recette - ( Forge ) - ( Niveau 1)", category="Livre de Recette", usage="Livre de Recette" },
    [14072948] = { name="Livre de Recette - ( Cuisine ) - ( Niveau 1)", category="Livre de Recette", usage="Livre de Recette" },
    [14072949] = { name="Livre de Recette - ( Tannerie ) - ( Niveau 1)", category="Livre de Recette", usage="Livre de Recette" },
    [14072950] = { name="Livre de Recette - ( Ingénierie ) - ( Niveau 1)", category="Livre de Recette", usage="Livre de Recette" },
    [14072951] = { name="Livre de Recette - ( Alchimie ) - ( Niveau 1)", category="Livre de Recette", usage="Livre de Recette" },
    [14072952] = { name="Livre de Recette - ( Couture ) - ( Niveau 1)", category="Livre de Recette", usage="Livre de Recette" },
    [14072954] = { name="Livre de Recette", category="Alchimie / Skoliag", usage="Nouvel objet scanner", notes="ID confirmé via scanner marchand" },
    [14072955] = { name="Livre de Recette", category="Couture / Skoliag", usage="Nouvel objet scanner", notes="ID confirmé via scanner marchand" },
    [14072963] = { name="Outils de Crochetage Renforcé", category="Objet / Consommable", usage="Objet / Consommable" },
    [14072966] = { name="Statuette Magnifique Divine", category="Dévotion / Outils", usage="Nouvel objet scanner", notes="ID confirmé via scanner marchand" },
    [14072968] = { name="Plume Enchantée", category="Objet / Maîtrise / Outils", usage="Nouvel objet scanner", notes="ID confirmé via scanner marchand" },
    [14072970] = { name="Encre Enchantée", category="Objet / Maîtrise / Outils", usage="Nouvel objet scanner", notes="ID confirmé via scanner marchand" },
    [14072976] = { name="Aquarelle Enchantée", category="Peinture / Maîtrise / Outils", usage="Nouvel objet scanner", notes="ID confirmé via scanner marchand" },
    [14072979] = { name="Crayon Enchanté", category="Objet / Maîtrise / Outils", usage="Nouvel objet scanner", notes="ID confirmé via scanner marchand" },
    [14072983] = { name="Petite Enclume Trandalion", category="Outil", usage="Outil" },
    [14072987] = { name="Foyer Trandalion", category="Outil", usage="Outil" },
    [14072989] = { name="Table d'Alchimie Transportable", category="Alchimie / Outils", usage="Nouvel objet scanner", notes="ID confirmé via scanner marchand" },
    [14072991] = { name="Petite Station de Tannage", category="Tannerie / Outils", usage="Nouvel objet scanner", notes="ID confirmé via scanner marchand" },
    [14072992] = { name="Métier à Tisser", category="Outil", usage="Outil" },
    [14072996] = { name="Lingot d'Acier", usage="Objet fabriqué + Composant", notes="ID confirmé via scanner marchand" },
    [14072997] = { name="Lingot de Cuivre", usage="Objet fabriqué + Composant", notes="ID confirmé via scanner marchand" },
    [14072998] = { name="Clous en Fer Noir", usage="Objet fabriqué + Composant", notes="ID confirmé via scanner marchand" },
    [14072999] = { name="Plaque en Acier", usage="Objet fabriqué + Composant", notes="ID confirmé via scanner marchand" },
    [14073001] = { name="Limaille de Cuivre", usage="Composant", notes="ID confirmé via scanner marchand" },
    [14073002] = { name="Lingot de Skodelite", usage="Objet fabriqué + Composant", notes="ID confirmé via scanner marchand" },
    [14073003] = { name="Lingot de Fer Noir", usage="Objet fabriqué + Composant", notes="ID confirmé via scanner marchand" },
    [14073005] = { name="Plaque de Skodelite", usage="Objet fabriqué + Composant", notes="ID confirmé via scanner marchand" },
    [14073006] = { name="Fil de Fer Noir", usage="Objet fabriqué + Composant", notes="ID confirmé via scanner marchand" },
    [14073007] = { name="Limaille de Fer Noir", usage="Composant", notes="ID confirmé via scanner marchand" },
    [14073018] = { name="Graisse de Porc", usage="Composant", notes="ID confirmé via scanner marchand" },
    [14073019] = { name="Farine de Froment", usage="Composant", notes="ID confirmé via scanner marchand" },
    [14073020] = { name="Légumes du Matin", usage="Composant", notes="ID confirmé via scanner marchand" },
    [14073021] = { name="Farine de Seigle Noir", usage="Composant", notes="ID confirmé via scanner marchand" },
    [14073022] = { name="Beurre Salé de Skoliag", usage="Composant", notes="ID confirmé via scanner marchand" },
    [14073023] = { name="Huile de Baleine", usage="Composant", notes="ID confirmé via scanner marchand" },
    [14073024] = { name="Lait de Chèvre des Montagne", usage="Composant", notes="ID confirmé via scanner marchand" },
    [14073026] = { name="Cuir Lourd des Géants", usage="Objet fabriqué + Composant", notes="ID confirmé via scanner marchand" },
    [14073027] = { name="Pierre Gravée de Runes", usage="Composant", notes="ID confirmé via scanner marchand" },
    [14073028] = { name="Morceau de Cuir Titanien", usage="Composant", notes="ID confirmé via scanner marchand" },
    [14073029] = { name="Bandes de Cuir des Géants", usage="Objet fabriqué + Composant", notes="ID confirmé via scanner marchand" },
    [14073030] = { name="Teinture aux Marrons", usage="Composant", notes="ID confirmé via scanner marchand" },
    [14073031] = { name="Cuir Souple des Géants", usage="Objet fabriqué + Composant", notes="ID confirmé via scanner marchand" },
    [14073032] = { name="Bandes de Cuir", usage="Objet fabriqué + Composant", notes="ID confirmé via scanner marchand" },
    [14073033] = { name="Cuir Souple", usage="Objet fabriqué + Composant", notes="ID confirmé via scanner marchand" },
    [14073034] = { name="Chaux Vive", usage="Composant", notes="ID confirmé via scanner marchand" },
    [14073035] = { name="Teinture en Broux de Noix", usage="Composant", notes="ID confirmé via scanner marchand" },
    [14073036] = { name="Cuir Lourd", usage="Objet fabriqué + Composant", notes="ID confirmé via scanner marchand" },
    [14073040] = { name="Rouages et Ressorts", usage="Composant", notes="ID confirmé via scanner marchand" },
    [14073041] = { name="Piston Simple", usage="Objet fabriqué + Composant", notes="ID confirmé via scanner marchand" },
    [14073042] = { name="Plaque de Pression", usage="Objet fabriqué + Composant", notes="ID confirmé via scanner marchand" },
    [14073043] = { name="Valve en Laiton", usage="Objet fabriqué + Composant", notes="ID confirmé via scanner marchand" },
    [14073044] = { name="Vilebrequin en Skodelite", usage="Objet fabriqué + Composant", notes="ID confirmé via scanner marchand" },
    [14073045] = { name="Soupape à Vapeur de Skard", usage="Objet fabriqué + Composant", notes="ID confirmé via scanner marchand" },
    [14073046] = { name="Tuyauterie Isolée", usage="Objet fabriqué + Composant", notes="ID confirmé via scanner marchand" },
    [14073047] = { name="Cardan de Transmission", usage="Composant", notes="ID confirmé via scanner marchand" },
    [14073048] = { name="Brûleur à Huile de Pin", usage="Composant", notes="ID confirmé via scanner marchand" },
    [14073049] = { name="Ressort de Compression", usage="Composant", notes="ID confirmé via scanner marchand" },
    [14073050] = { name="Laine", usage="Composant", notes="ID confirmé via scanner marchand" },
    [14073051] = { name="Lin", usage="Composant", notes="ID confirmé via scanner marchand" },
    [14073052] = { name="Boulons et Écrous", usage="Composant", notes="ID confirmé via scanner marchand" },
    [14073053] = { name="Engrenages et Courroies", usage="Composant", notes="ID confirmé via scanner marchand" },
    [14073054] = { name="Fil", usage="Objet fabriqué + Composant", notes="ID confirmé via scanner marchand" },
    [14073055] = { name="Etoffe de Laine de Skoliag", usage="Objet fabriqué + Composant", notes="ID confirmé via scanner marchand" },
    [14073056] = { name="Fil teint en Marron", usage="Composant", notes="ID confirmé via scanner marchand" },
    [14073057] = { name="Etoffe de Lin de Skoliag", usage="Objet fabriqué + Composant", notes="ID confirmé via scanner marchand" },
    [14073058] = { name="Étoffe de Coton", usage="Objet fabriqué + Composant", notes="ID confirmé via scanner marchand" },
    [14073059] = { name="Tissu Renforcé", usage="Objet fabriqué + Composant", notes="ID confirmé via scanner marchand" },
    [14073060] = { name="Étoffe de Laine", usage="Objet fabriqué + Composant", notes="ID confirmé via scanner marchand" },
    [14073061] = { name="Tissu Mélangé", usage="Objet fabriqué + Composant", notes="ID confirmé via scanner marchand" },
    [14073062] = { name="Coton", usage="Composant", notes="ID confirmé via scanner marchand" },
    [14073063] = { name="Étoffe de Lin", usage="Objet fabriqué + Composant", notes="ID confirmé via scanner marchand" },
    [14073064] = { name="Laine de Skoliag", usage="Composant", notes="ID confirmé via scanner marchand" },
    [14073065] = { name="Tissus Mélangés de Skoliag", usage="Objet fabriqué + Composant", notes="ID confirmé via scanner marchand" },
    [14073066] = { name="Lin de Skoliag", usage="Composant", notes="ID confirmé via scanner marchand" },
    [14073070] = { name="Elixir de Compétence", category="Elixir / Consommable", usage="Nouvel objet scanner", notes="ID confirmé via scanner marchand" },
    [14073084] = { name="Gantelet Maître du Temps", category="Secondaire / Spécial / Equipement", usage="Nouvel objet scanner", notes="ID confirmé via scanner marchand" },
    [14073092] = { name="Certificat de Location de Monture", category="Document", usage="Nouvel objet scanner", notes="ID confirmé via scanner marchand" },
    [14073094] = { name="Bourse en Cuir Usée", category="Bourse", profession="10 Pièces d'Or", usage="Nouvel objet scanner", notes="ID confirmé via scanner marchand" },
    [14073095] = { name="Bourse en Cuir Simple", category="Bourse", profession="20 Pièces d'Or", usage="Nouvel objet scanner", notes="ID confirmé via scanner marchand" },
    [14073096] = { name="Bourse en Cuir Renforcé", category="Bourse", profession="50 Pièces d'Or", usage="Nouvel objet scanner", notes="ID confirmé via scanner marchand" },
    [14073097] = { name="Bourse en Cuir Épais", category="Bourse", profession="100 Pièces d'Or", usage="Nouvel objet scanner", notes="ID confirmé via scanner marchand" },
    [14073113] = { name="Anneau Runique", usage="Objet fabriqué + Composant", notes="ID confirmé via scanner marchand" },
    [14073114] = { name="Essence Runique", usage="Composant", notes="ID confirmé via scanner marchand" },
    [14073115] = { name="Essence Astrale", usage="Composant", notes="ID confirmé via scanner marchand" },
    [14073155] = { name="Jeton de Foi", category="Monnaie", usage="Monnaie" },
    [14073241] = { name="Livre de Recette - ( Couture ) - ( Niveau 0)", category="Livre de Recette", usage="Livre de Recette" },
    [14073242] = { name="Livre de Recette - ( Tannerie ) - ( Niveau 0)", category="Livre de Recette", usage="Livre de Recette" },
    [14073243] = { name="Sac ( 6 )", usage="Objet fabriqué", notes="ID confirmé via scanner marchand" },
    [14073244] = { name="Sac ( 10 )", usage="Objet fabriqué", notes="ID confirmé via scanner marchand" },
    [14073245] = { name="Sac ( 8 )", usage="Objet fabriqué", notes="ID confirmé via scanner marchand" },
    [14073246] = { name="Vêtement Simple I", usage="Objet fabriqué", notes="ID confirmé via scanner marchand" },
    [14073247] = { name="Vêtement Habillé I", usage="Objet fabriqué", notes="ID à renseigner" },
    [14073249] = { name="Vêtement Chaud I", usage="Objet fabriqué", notes="ID confirmé via scanner marchand" },
    [14073260] = { name="Tunique des Routes Ouvertes", usage="Objet fabriqué", notes="ID confirmé via scanner marchand" },
    [14073261] = { name="Chemise Matelassée du Voyageur", usage="Objet fabriqué", notes="ID confirmé via scanner marchand" },
    [14073262] = { name="Pourpoint Souple de Rôdeur", usage="Objet fabriqué", notes="ID confirmé via scanner marchand" },
    [14073263] = { name="Gilet Renforcé de Milice", usage="Objet fabriqué", notes="ID confirmé via scanner marchand" },
    [14073264] = { name="Capuchon du Guetteur", usage="Objet fabriqué", notes="ID confirmé via scanner marchand" },
    [14073265] = { name="Capuche en Tissu Rembourré", usage="Objet fabriqué", notes="ID confirmé via scanner marchand" },
    [14073266] = { name="Coiffe de Toile Épaisse", usage="Objet fabriqué", notes="ID confirmé via scanner marchand" },
    [14073267] = { name="Bandeau de l'Érudit", usage="Objet fabriqué", notes="ID confirmé via scanner marchand" },
    [14073268] = { name="Cuirasse Mixte d'Avant-Garde", usage="Objet fabriqué", notes="ID confirmé via scanner marchand" },
    [14073269] = { name="Armure Rivetée du Garde", usage="Objet fabriqué", notes="ID confirmé via scanner marchand" },
    [14073270] = { name="Plastron du Bastion", usage="Objet fabriqué", notes="ID confirmé via scanner marchand" },
    [14073271] = { name="Cuirasse d'Acier Brut", usage="Objet fabriqué", notes="ID confirmé via scanner marchand" },
    [14073272] = { name="Casque Renforcé de Légion", usage="Objet fabriqué", notes="ID confirmé via scanner marchand" },
    [14073273] = { name="Casque à Nasal du Fantassin", usage="Objet fabriqué", notes="ID confirmé via scanner marchand" },
    [14073274] = { name="Heaume Intégral", usage="Objet fabriqué", notes="ID confirmé via scanner marchand" },
    [14073275] = { name="Grand Heaume du Rempart", usage="Objet fabriqué", notes="ID confirmé via scanner marchand" },
    [14073276] = { name="Veste de Cuir Renforcé", usage="Objet fabriqué", notes="ID confirmé via scanner marchand" },
    [14073278] = { name="Capeline de Cuir Durci", usage="Objet fabriqué", notes="ID confirmé via scanner marchand" },
    [14073279] = { name="Gants Renforcés", usage="Objet fabriqué", notes="ID confirmé via scanner marchand" },
    [14073280] = { name="Gants en Cuir Épais", usage="Objet fabriqué", notes="ID confirmé via scanner marchand" },
    [14073281] = { name="Bottes de Cuir", usage="Objet fabriqué", notes="ID confirmé via scanner marchand" },
    [14073282] = { name="Bottes du Pisteur", usage="Objet fabriqué", notes="ID confirmé via scanner marchand" },
    [14073283] = { name="Ceinture de Force", usage="Objet fabriqué", notes="ID confirmé via scanner marchand" },
    [14073284] = { name="Ceinture à Outils en Cuir", usage="Objet fabriqué", notes="ID confirmé via scanner marchand" },
    [14073285] = { name="Cape de Peaux", usage="Objet fabriqué", notes="ID confirmé via scanner marchand" },
    [14073286] = { name="Cape de Voyageur Endurci", usage="Objet fabriqué", notes="ID confirmé via scanner marchand" },
    [14073287] = { name="Elixir de Vitesse I", usage="Objet fabriqué", notes="ID confirmé via scanner marchand" },
    [14073288] = { name="Elixir de Vie I", usage="Objet fabriqué", notes="ID confirmé via scanner marchand" },
    [14073289] = { name="Elixir de Protection : Magique I", usage="Objet fabriqué", notes="ID confirmé via scanner marchand" },
    [14073290] = { name="Elixir de Protection : Physique I", usage="Objet fabriqué", notes="ID confirmé via scanner marchand" },
    [14073291] = { name="Elixir de Vigueur I", usage="Objet fabriqué", notes="ID confirmé via scanner marchand" },
    [14073292] = { name="Elixir de Maîtrise I", usage="Objet fabriqué", notes="ID confirmé via scanner marchand" },
    [14073293] = { name="Ragoût Réconfortant", usage="Objet fabriqué", notes="ID confirmé via scanner marchand" },
    [14073294] = { name="Plat du Marcheur", usage="Objet fabriqué", notes="ID confirmé via scanner marchand" },
    [14073295] = { name="Potage des Eaux Claires", usage="Objet fabriqué", notes="ID confirmé via scanner marchand" },
    [14073296] = { name="Brochette du Brasier Doux", usage="Objet fabriqué", notes="ID confirmé via scanner marchand" },
    [14073297] = { name="Soufflé des Hautes Brises", usage="Objet fabriqué", notes="ID confirmé via scanner marchand" },
    [14073298] = { name="Tourte des Racines", usage="Objet fabriqué", notes="ID confirmé via scanner marchand" },
    [14073299] = { name="Mécanisme de Vision 2.0 I", usage="Objet fabriqué", notes="ID confirmé via scanner marchand" },
    [14073300] = { name="Mécanisme de Vision 1.0 I", usage="Objet fabriqué", notes="ID confirmé via scanner marchand" },
    [14073301] = { name="Mécanisme de Défense I : Magique", usage="Objet fabriqué", notes="ID confirmé via scanner marchand" },
    [14073302] = { name="Mécanisme de Défense I : Physique", usage="Objet fabriqué", notes="ID confirmé via scanner marchand" },
    [14073303] = { name="Mécanisme d'Attaque I : Physique", usage="Objet fabriqué", notes="ID confirmé via scanner marchand" },
    [14073304] = { name="Mécanisme d'Attaque I : Magique", usage="Objet fabriqué", notes="ID confirmé via scanner marchand" },
    [14073341] = { name="Eau Bénite du Temple", usage="Composant", notes="ID confirmé via scanner marchand" },
    [14073342] = { name="Anneau Astral", usage="Objet fabriqué + Composant", notes="ID confirmé via scanner marchand" },
    [14073344] = { name="Mécanisme de Puissance Titanien", usage="Objet fabriqué", notes="ID confirmé via scanner marchand" },
    [14073345] = { name="Mécanisme du Combattant Titanien", usage="Objet fabriqué", notes="ID confirmé via scanner marchand" },
    [14073346] = { name="Mécanisme d'Endurance Titanien", usage="Objet fabriqué", notes="ID confirmé via scanner marchand" },
    [14073347] = { name="Mécanisme de Vitalité Titanien", usage="Objet fabriqué", notes="ID confirmé via scanner marchand" },
    [14073348] = { name="Elixir de Soin de Skoliag", usage="Objet fabriqué", notes="ID confirmé via scanner marchand" },
    [14073349] = { name="Elixir de Vigueur de Skoliag", usage="Objet fabriqué", notes="ID confirmé via scanner marchand" },
    [14073350] = { name="Elixir de Défenses de Skoliag", usage="Objet fabriqué", notes="ID confirmé via scanner marchand" },
    [14073351] = { name="Elixir du Froid Blanc", usage="Objet fabriqué", notes="ID confirmé via scanner marchand" },
    [14073352] = { name="Bouillon du Fjord", usage="Objet fabriqué", notes="ID confirmé via scanner marchand" },
    [14073353] = { name="Pain Noir du Chasseur", usage="Objet fabriqué", notes="ID confirmé via scanner marchand" },
    [14073354] = { name="Viande Fumée de Skoliag", usage="Objet fabriqué", notes="ID confirmé via scanner marchand" },
    [14073355] = { name="Ragoût des Hautes Glaces", usage="Objet fabriqué", notes="ID confirmé via scanner marchand" },
    [14073357] = { name="Bottes en Cuir de Skoliag", usage="Objet fabriqué", notes="ID confirmé via scanner marchand" },
    [14073358] = { name="Ceinture Lourde de Skoliag", usage="Objet fabriqué", notes="ID confirmé via scanner marchand" },
    [14073359] = { name="Gants Résistants de Skoliag", usage="Objet fabriqué", notes="ID confirmé via scanner marchand" },
    [14073360] = { name="Cape Lourde de Skoliag", usage="Objet fabriqué", notes="ID confirmé via scanner marchand" },
    [14073361] = { name="Capuche de l'Œil Boréal", usage="Objet fabriqué", notes="ID confirmé via scanner marchand" },
    [14073362] = { name="Heaume de Peau-Rime", usage="Objet fabriqué", notes="ID confirmé via scanner marchand" },
    [14073363] = { name="Bassinet du Souffle Pâle", usage="Objet fabriqué", notes="ID confirmé via scanner marchand" },
    [14073364] = { name="Casque de l'Hiver Immobile", usage="Objet fabriqué", notes="ID confirmé via scanner marchand" },
    [14073365] = { name="Plastron du Froid Enchaîné", usage="Objet fabriqué", notes="ID confirmé via scanner marchand" },
    [14073366] = { name="Cuirasse du Mur de Glace", usage="Objet fabriqué", notes="ID confirmé via scanner marchand" },
    [14073367] = { name="Casaque de Veine Blanche", usage="Objet fabriqué", notes="ID confirmé via scanner marchand" },
    [14073369] = { name="Robe de Givre Runique", usage="Objet fabriqué", notes="ID confirmé via scanner marchand" },
    [14073505] = { name="Vodka Amoréenne", category="Objet / Consommable", usage="Objet / Consommable" },
    [14073524] = { name="Fil de Cuivre", usage="Objet fabriqué + Composant", notes="ID confirmé via scanner marchand" },
    [14073572] = { name="Marque de l'Hiver", category="Objet", usage="Nouvel objet scanner", notes="ID confirmé via scanner marchand" },
    [14073580] = { name="Sang de Prométhée", category="Composant / Heljar", usage="Nouvel objet scanner", notes="ID confirmé via scanner marchand" },
    [14073582] = { name="Éclat de Bois nimbé de Chaos", category="Composant / Heljar", usage="Nouvel objet scanner", notes="ID confirmé via scanner marchand" },
    [14073593] = { name="Elixir Strygir de l'Hiver Blanc", category="Elixir / Consommable / Heljar", usage="Nouvel objet scanner", notes="ID confirmé via scanner marchand" },
    [14073594] = { name="Effigie d'Os et de Bois", category="Cou / Heljar", usage="Nouvel objet scanner", notes="ID confirmé via scanner marchand" },
    [14073595] = { name="Bague de l'Eternel Hiver", category="Bijoux / Niveau 0 / Heljar", usage="Nouvel objet scanner", notes="ID confirmé via scanner marchand" },
    [14073596] = { name="Bague de l'Eternel Hiver", category="Bijoux / Niveau 1 / Heljar", usage="Nouvel objet scanner", notes="ID confirmé via scanner marchand" },
    [14073598] = { name="Bague de l'Eternel Hiver", category="Bijoux / Niveau 3 / Heljar", usage="Nouvel objet scanner", notes="ID confirmé via scanner marchand" },
    [14073599] = { name="Bague de l'Eternel Hiver", category="Bijoux / Niveau 4 / Heljar", usage="Nouvel objet scanner", notes="ID confirmé via scanner marchand" },
    [14073601] = { name="Bague de l'Eternel Hiver", category="Bijoux / Niveau 5 / Heljar", usage="Nouvel objet scanner", notes="ID confirmé via scanner marchand" },
    [14073620] = { name="Lame d'Eon, Courbure du temps", category="Armement / Légère", usage="Nouvel objet scanner", notes="ID confirmé via scanner marchand" },
    [14073734] = { name="Eau", category="Objet / Consommable", usage="Objet / Consommable" },
    [14073735] = { name="Verre", category="Composant", usage="Composant" },
    [14076445] = { name="Planche de Bois", category="Composant", usage="Composant" },
}
